import "../bootstrap-5.3.2/scss/bootstrap.scss";
import "../bootstrap-5.3.2/scss/bootstrap-utilities.scss";
import "../bootstrap-5.3.2/scss/bootstrap-reboot.scss";
import "../bootstrap-5.3.2/scss/bootstrap-grid.scss";
import "./crud";
import "./validation";
import "./productos";
import "./carro";
// import "./weather";
import "../scss/styles.scss";
